In [ ]:
import os,sys
sys.path.append('../..')
sys.path.append('../../../gempy/')
import gempy as gp
import time

#os.environ["THEANO_FLAGS"] = "mode=FAST_RUN,device=cuda"
os.environ["THEANO_FLAGS"] = "mode=FAST_RUN"
import sandbox.sandbox as sb


#import gempy_sandbox a   s gpsb
import numpy as np
#from PIL import Image, ImageDraw
import pickle

In [ ]:
calibrationdata = sb.CalibrationData(file='my_calibration.json')
sensor = sb.KinectV2(calibrationdata)
projector = sb.Projector(calibrationdata)

In [ ]:
tempfile = 'temp.pickle.pickle'
last_time_modified = os.path.getmtime(tempfile)
geo_model=gp.load_model_pickle(tempfile)

In [4]:
def update_model(tempfile):
    print('updating model')
    gpsb.stop()
    geo_model = gp.load_model_pickle(tempfile)
    gpsb.geo_model = geo_model
    gpsb.setup()
    gpsb.run()
    

In [5]:
gpsb=sb.GemPyModule(geo_model, calibrationdata, sensor, projector)

In [6]:
gpsb.setup()

Aspect ratio of the model is fixed in XY
Model size is limited by X dimension
scale in Model units/ mm (X,Y,Z): [4.0, 4.084249084249084, 2.5]
the shown extent is [4000.0, 0.0, 0.0, 2775.0] 
the shown extent is [4000.0, 0.0, 0.0, 2775.0] 


In [7]:
gpsb.run()


Thread started or resumed...


In [11]:
update_model(tempfile)

updating model
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
Thread stopped.
Aspect ratio of the model is fixed in XY
Model size is limited by X dimension
scale in Model units/ mm (X,Y,Z): [4.0, 4.084249084249084, 2.5]
the shown extent is [4000.0, 0.0, 0.0, 2775.0] 
the shown extent is [4000.0, 0.0, 0.0, 2775.0] 
Thread started or resumed...
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
n

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b _

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __s

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b _

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0]
a __str__ = [0 1]
nsle __str__ = 1
is_erosion __str__ = [1 0 0]
b __str__ = [1 0 0]
a __str__ = [0 1]
nsle __str__ = 1
[0 1 2]
[Erosion, Fault, Erosion]
Categories (3, object): [Erosion, Onlap, Fault]
is_erosion [ True False False]
is_erosion __str__ = [1 0 0]
b __str__ = [1]
a __str__ = [0 1]
nsle __str__ = 1
is_er

In [ ]:
gpsb.stop()